# Generated by Django 4.2.6 on 2023-11-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nome')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nome')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='descrição')),
                ('category_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryprimary')),
            ],
        ),
    ]
