# Generated by Django 4.2.6 on 2023-11-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category_primary',
        ),
        migrations.DeleteModel(
            name='CategoryPrimary',
        ),
        migrations.DeleteModel(
            name='ColorProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
