# Generated by Django 4.2.6 on 2023-11-04 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_remove_product_category_remove_product_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nome')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='Cor')),
                ('url', models.URLField(verbose_name='Imagem da Cor')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nome')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='descrição')),
                ('category_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryprimary')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.IntegerField(verbose_name='Web ID')),
                ('product_title', models.CharField(max_length=400, verbose_name='Titulo')),
                ('image', models.URLField(verbose_name='Imagem')),
                ('alternative_image', models.URLField(verbose_name='Imagem alternativa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('average_rating', models.FloatField(verbose_name='Média de avaliações')),
                ('count_rating', models.IntegerField(verbose_name='Quantidade de avaliações')),
                ('display_color', models.CharField(max_length=100, verbose_name='Cor atual')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
                ('color', models.ManyToManyField(related_name='products', to='products.colorproduct', verbose_name='Imagens das Cores Disponiveis')),
            ],
        ),
    ]
