# Generated by Django 4.2.6 on 2023-11-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alternative_image',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem alternativa'),
        ),
    ]
