# Generated by Django 4.2.6 on 2023-11-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_alternative_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Média de avaliações'),
        ),
    ]
