# Generated by Django 4.2.6 on 2023-11-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de avaliações'),
        ),
    ]
