# Generated by Django 4.2.6 on 2023-11-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_slug'),
    ]

    operations = [
        
    ]
